version: '2'
services:
  mongodb-server:
    container_name: mongodb-server
    image: mongo
    ports:
      - "27017:27017"
  redis-server:
    container_name: redis-server
    image: redis:alpine
    ports:
      - "6379:6379"
